name: Build All Wheels for Repository

on: workflow_dispatch
  
jobs:
  run_workflow_0-37-2:
    name: Build Wheels 0.37.2
    uses: ./.github/workflows/build-windows-0.37.2-repo.yml
    
  run_workflow_0-38-1:
    name: Build Wheels 0.38.1
    needs: run_workflow_0-37-2
    uses: ./.github/workflows/build-windows-0.38.1-repo.yml
    
  run_workflow_0-39-0:
    name: Build Wheels 0.39.0
    needs: run_workflow_0-38-1
    uses: ./.github/workflows/build-windows-0.39.0-repo.yml
