name: Test Workflow

on: workflow_dispatch

jobs:
  compile_cuda:
    name: Test Install Cuda 11.1.1
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Install Cuda Toolkit
        uses: Jimver/cuda-toolkit@v0.2.10
        with:
          cuda: '11.1.1'
          method: 'network'
          sub-packages: '["nvcc", "visual_studio_integration"]'
          
      - name: Check Directories
        run: |
          echo $env:CUDA_PATH + "`n`n"
          dir $env:CUDA_PATH -recurse
          dir 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\*\BuildCustomizations'
